version: "3"
services:
    backend:
        build:
            dockerfile: Dockerfile
            context: ./backend
        command: sh ./start.sh
        ports:
            - 5000:5000
        volumes:
            - ./backend/src:/app
        environment:
            FLASK_ENV: development
